# Generated by Django 5.2b1 on 2025-03-21 01:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('address', models.TextField(default='')),
                ('phone', models.CharField(default='', max_length=15, validators=[django.core.validators.RegexValidator(message='Please enter the right phone number', regex='^[\\+]?[(]?[0-9]{3}[)]?[-\\s\\.]?[0-9]{3}[-\\s\\.]?[0-9]{4,6}$')])),
                ('ice', models.CharField(default='', max_length=15, validators=[django.core.validators.RegexValidator(message='Please enter the right ICE number', regex='^\\d{1,15}$'), django.core.validators.MinLengthValidator(15, 'the field must contain 15 numbers')])),
            ],
        ),
    ]
