# Generated by Django 5.2b1 on 2025-03-21 01:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeCaution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_caution', models.CharField(choices=[('Définitive', 'Définitive'), ('Provisoire', 'Provisoire'), ('Retenue de garantie', 'Retenue de garantie')], max_length=20)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=15)),
                ('administration_interessee', models.CharField(max_length=100, verbose_name='Administration intéressée')),
                ('nature_travaux', models.TextField(verbose_name='Nature des travaux')),
                ('numero_marche', models.CharField(max_length=50, verbose_name='Numéro de marché')),
                ('AON', models.CharField(max_length=50, verbose_name='A.O.N')),
                ('delai_execution_marche', models.CharField(choices=[('1 mois', '1 mois'), ('2 mois', '2 mois'), ('3 mois', '3 mois'), ('4 mois', '4 mois'), ('5 mois', '5 mois'), ('6 mois', '6 mois'), ('7 mois', '7 mois'), ('8 mois', '8 mois'), ('9 mois', '9 mois'), ('10 mois', '10 mois'), ('11 mois', '11 mois'), ('12 mois', '12 mois')], max_length=100, verbose_name="Délai d'exécution du marché")),
                ('delai_prononciation_reception', models.CharField(choices=[('12 mois', '12 mois'), ('2 ans', '2 ans'), ('3 ans', '3 ans'), ('4 ans', '4 ans'), ('5 ans', '5 ans'), ('6 ans', '6 ans'), ('7 ans', '7 ans'), ('8 ans', '8 ans'), ('9 ans', '9 ans'), ('10 ans', '10 ans')], max_length=100, verbose_name='Délai fixe pour la prononciation de la réception définitive')),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DemandeVirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulaire', models.CharField(max_length=50, verbose_name='Titulaire')),
                ('rib', models.CharField(max_length=24, validators=[django.core.validators.MinLengthValidator(24, 'the rib must contain 24 numbers')])),
                ('montant', models.DecimalField(decimal_places=2, max_digits=15)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
