# Generated by Django 5.2b1 on 2025-03-21 01:06

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('services', '0001_initial'),
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrderOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_order_out', to='suppliers.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrderOutProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('price_at_purchase_order', models.DecimalField(decimal_places=2, max_digits=15)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_order_out_product', to='products.product')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_order_out_product', to='purchase_orders.purchaseorderout')),
            ],
        ),
        migrations.AddField(
            model_name='purchaseorderout',
            name='products',
            field=models.ManyToManyField(blank=True, through='purchase_orders.PurchaseOrderOutProduct', to='products.product'),
        ),
        migrations.CreateModel(
            name='PurchaseOrderOutService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('price_at_purchase_order', models.DecimalField(decimal_places=2, max_digits=15)),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_order_out_service', to='purchase_orders.purchaseorderout')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_order_out_service', to='services.service')),
            ],
        ),
        migrations.AddField(
            model_name='purchaseorderout',
            name='services',
            field=models.ManyToManyField(blank=True, through='purchase_orders.PurchaseOrderOutService', to='services.service'),
        ),
    ]
