# Generated by Django 5.2b1 on 2025-03-21 01:06

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('products', '0001_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('is_converted', models.BooleanField(default=False)),
                ('invoice_id', models.IntegerField(blank=True, default=0, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='clients.client')),
            ],
        ),
        migrations.CreateModel(
            name='QuoteOutProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('price_at_quote', models.DecimalField(decimal_places=2, max_digits=15)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote_out_product', to='products.product')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote_out_product', to='quotes.quoteout')),
            ],
        ),
        migrations.AddField(
            model_name='quoteout',
            name='products',
            field=models.ManyToManyField(blank=True, through='quotes.QuoteOutProduct', to='products.product'),
        ),
        migrations.CreateModel(
            name='QuoteOutService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('price_at_quote', models.DecimalField(decimal_places=2, max_digits=15)),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote_out_service', to='quotes.quoteout')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote_out_service', to='services.service')),
            ],
        ),
        migrations.AddField(
            model_name='quoteout',
            name='services',
            field=models.ManyToManyField(blank=True, through='quotes.QuoteOutService', to='services.service'),
        ),
    ]
